// Temporary mock data — will be replaced by MySQL/Prisma queries in the next phase.
// Structure mirrors the DB schema so the swap is a 1-line change per page.

import type { Product, Category, Brand, StoreSettings } from '@/types';

export const MOCK_SETTINGS: StoreSettings = {
  id: 1,
  store_name: 'Yasser Phone',
  slogan: 'Premium Mobile Store',
  logo_url: null,
  whatsapp_number: '22232816779',
  phone: '+222 32 81 67 79',
  email: 'contact@yasserphone.mr',
  address: 'نواكشوط — النقطة الساخنة',
  city: 'نواكشوط',
  currency: 'MRU',
  facebook_url: 'https://facebook.com/yasserphone',
  instagram_url: 'https://instagram.com/yasserphone',
  tiktok_url: 'https://tiktok.com/@yasserphone',
};

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name_ar: 'هواتف ذكية',   slug: 'phones',      image_url: null, sort_order: 1, is_active: true },
  { id: 2, name_ar: 'سماعات',       slug: 'audio',       image_url: null, sort_order: 2, is_active: true },
  { id: 3, name_ar: 'ساعات ذكية',   slug: 'watches',     image_url: null, sort_order: 3, is_active: true },
  { id: 4, name_ar: 'شواحن',        slug: 'chargers',    image_url: null, sort_order: 4, is_active: true },
  { id: 5, name_ar: 'إكسسوارات',   slug: 'accessories', image_url: null, sort_order: 5, is_active: true },
  { id: 6, name_ar: 'باور بانك',    slug: 'powerbanks',  image_url: null, sort_order: 6, is_active: true },
  { id: 7, name_ar: 'حافظات',       slug: 'cases',       image_url: null, sort_order: 7, is_active: true },
  { id: 8, name_ar: 'كابلات',       slug: 'cables',      image_url: null, sort_order: 8, is_active: true },
];

export const MOCK_BRANDS: Brand[] = [
  { id: 1, name: 'Apple',   slug: 'apple',   logo_url: null, is_active: true },
  { id: 2, name: 'Samsung', slug: 'samsung', logo_url: null, is_active: true },
  { id: 3, name: 'Xiaomi',  slug: 'xiaomi',  logo_url: null, is_active: true },
  { id: 4, name: 'Tecno',   slug: 'tecno',   logo_url: null, is_active: true },
  { id: 5, name: 'Infinix', slug: 'infinix', logo_url: null, is_active: true },
  { id: 6, name: 'Huawei',  slug: 'huawei',  logo_url: null, is_active: true },
  { id: 7, name: 'Oppo',    slug: 'oppo',    logo_url: null, is_active: true },
  { id: 8, name: 'Realme',  slug: 'realme',  logo_url: null, is_active: true },
];

const apple  = MOCK_BRANDS[0];
const samsung = MOCK_BRANDS[1];
const xiaomi  = MOCK_BRANDS[2];
const tecno   = MOCK_BRANDS[3];
const infinix = MOCK_BRANDS[4];
const huawei  = MOCK_BRANDS[5];
const oppo    = MOCK_BRANDS[6];
const realme  = MOCK_BRANDS[7];

const phones      = MOCK_CATEGORIES[0];
const audio       = MOCK_CATEGORIES[1];
const watches     = MOCK_CATEGORIES[2];
const chargers    = MOCK_CATEGORIES[3];
const accessories = MOCK_CATEGORIES[4];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1, name_ar: 'آيفون 15 برو ماكس', slug: 'iphone-15-pro-max',
    description_ar: 'هاتف iPhone 15 Pro Max الجديد بشاشة Super Retina XDR قياس 6.7 إنش، معالج A17 Pro، كاميرا ثلاثية 48 ميجابكسل مع زوم بصري 5x، وهيكل من التيتانيوم.',
    price: 58000, old_price: 62000, discount_percent: 6, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=800&q=80',
    condition: 'new', storage: '256GB', ram: '8GB', color: 'Natural Titanium',
    warranty: '12 شهر', is_featured: true, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.8, review_count: 59, bought_recently: 53,
    brand: apple, category: phones,
    images: [
      { id: 1, image_url: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=800&q=80', sort_order: 0 },
      { id: 2, image_url: 'https://images.unsplash.com/photo-1696446702183-be1cb88a9eda?w=800&q=80', sort_order: 1 },
    ],
    specs: [
      { id: 1, spec_name: 'الشاشة', spec_value: '6.7" Super Retina XDR' },
      { id: 2, spec_name: 'المعالج', spec_value: 'A17 Pro' },
      { id: 3, spec_name: 'الكاميرا', spec_value: '48MP Triple' },
      { id: 4, spec_name: 'البطارية', spec_value: '4422 mAh' },
    ],
  },
  {
    id: 2, name_ar: 'سامسونج جالاكسي S24 الترا', slug: 'samsung-galaxy-s24-ultra',
    description_ar: 'سامسونج جالاكسي S24 الترا بشاشة Dynamic AMOLED 2X بقياس 6.8 إنش، معالج Snapdragon 8 Gen 3 وقلم S Pen، كاميرا 200 ميجابكسل.',
    price: 52000, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
    condition: 'new', storage: '512GB', ram: '12GB', color: 'Titanium Black',
    warranty: '12 شهر', is_featured: true, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.4, review_count: 560, bought_recently: 364,
    brand: samsung, category: phones,
    images: [{ id: 3, image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80', sort_order: 0 }],
    specs: [
      { id: 5, spec_name: 'الشاشة', spec_value: '6.8" QHD+ AMOLED' },
      { id: 6, spec_name: 'المعالج', spec_value: 'Snapdragon 8 Gen 3' },
      { id: 7, spec_name: 'الكاميرا', spec_value: '200MP Quad' },
    ],
  },
  {
    id: 3, name_ar: 'شاومي 14 الترا', slug: 'xiaomi-14-ultra',
    description_ar: 'شاومي 14 الترا مع كاميرا Leica رباعية وعدسة بريسكوب 5x، شاشة LTPO AMOLED، ومعالج Snapdragon 8 Gen 3.',
    price: 42000, old_price: 46000, discount_percent: 9, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&q=80',
    condition: 'new', storage: '512GB', ram: '16GB', color: 'White',
    warranty: '12 شهر', is_featured: true, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 3.8, review_count: 94, bought_recently: 75,
    brand: xiaomi, category: phones,
    images: [{ id: 4, image_url: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&q=80', sort_order: 0 }],
    specs: [
      { id: 8, spec_name: 'الشاشة', spec_value: '6.73" LTPO AMOLED' },
      { id: 9, spec_name: 'المعالج', spec_value: 'Snapdragon 8 Gen 3' },
    ],
  },
  {
    id: 4, name_ar: 'إيربودز برو 2', slug: 'airpods-pro-2',
    description_ar: 'سماعات AirPods Pro 2 مع إلغاء الضوضاء النشط، شريحة H2، وعلبة شحن MagSafe USB-C.',
    price: 6500, old_price: 7200, discount_percent: 10, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'White',
    warranty: '12 شهر', is_featured: true, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.4, review_count: 560, bought_recently: 408,
    brand: apple, category: audio,
    images: [{ id: 5, image_url: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 10, spec_name: 'البطارية', spec_value: '6h + 30h case' }],
  },
  {
    id: 5, name_ar: 'ساعة آبل سيريس 9', slug: 'apple-watch-series-9',
    description_ar: 'ساعة Apple Watch Series 9 بشاشة Retina دائمة الإضاءة، شريحة S9، وميزات صحية متقدمة.',
    price: 12500, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Midnight',
    warranty: '12 شهر', is_featured: true, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 3.9, review_count: 129, bought_recently: 97,
    brand: apple, category: watches,
    images: [{ id: 6, image_url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 11, spec_name: 'الشاشة', spec_value: '1.9" Retina' }],
  },
  {
    id: 6, name_ar: 'سامسونج جالاكسي بادز 3 برو', slug: 'samsung-galaxy-buds3-pro',
    description_ar: 'سماعات Galaxy Buds3 Pro بصوت Hi-Fi 24-bit وإلغاء ضوضاء تكيفي.',
    price: 4800, old_price: 5500, discount_percent: 13, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Silver',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.5, review_count: 631, bought_recently: 408,
    brand: samsung, category: audio,
    images: [{ id: 7, image_url: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 12, spec_name: 'البطارية', spec_value: '7h + 30h case' }],
  },
  {
    id: 7, name_ar: 'آيفون 14', slug: 'iphone-14',
    description_ar: 'آيفون 14 بشاشة Super Retina XDR 6.1 إنش وكاميرا مزدوجة 12 ميجابكسل.',
    price: 38000, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=800&q=80',
    condition: 'new', storage: '128GB', ram: '6GB', color: 'Blue',
    warranty: '12 شهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 3.9, review_count: 165, bought_recently: 119,
    brand: apple, category: phones,
    images: [{ id: 8, image_url: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=800&q=80', sort_order: 0 }],
    specs: [
      { id: 13, spec_name: 'الشاشة', spec_value: '6.1" Super Retina XDR' },
      { id: 14, spec_name: 'المعالج', spec_value: 'A15 Bionic' },
    ],
  },
  {
    id: 8, name_ar: 'شاومي ريدمي نوت 13 برو', slug: 'redmi-note-13-pro',
    description_ar: 'ريدمي نوت 13 برو بكاميرا 200 ميجابكسل وشاشة AMOLED 120 هرتز.',
    price: 14500, old_price: 16000, discount_percent: 9, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80',
    condition: 'new', storage: '256GB', ram: '8GB', color: 'Forest Green',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.5, review_count: 667, bought_recently: 430,
    brand: xiaomi, category: phones,
    images: [{ id: 9, image_url: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80', sort_order: 0 }],
    specs: [
      { id: 15, spec_name: 'الشاشة', spec_value: '6.67" AMOLED 120Hz' },
      { id: 16, spec_name: 'الكاميرا', spec_value: '200MP Triple' },
    ],
  },
  {
    id: 9, name_ar: 'تكنو كامون 30 برو', slug: 'tecno-camon-30-pro',
    description_ar: 'تكنو كامون 30 برو مع كاميرا Sony LYT-600 وشاشة AMOLED 6.78 إنش.',
    price: 11500, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&q=80',
    condition: 'new', storage: '256GB', ram: '12GB', color: 'Basaltic Dark',
    warranty: '12 شهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.0, review_count: 200, bought_recently: 141,
    brand: tecno, category: phones,
    images: [{ id: 10, image_url: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 17, spec_name: 'الشاشة', spec_value: '6.78" AMOLED' }],
  },
  {
    id: 10, name_ar: 'إنفنكس نوت 40 برو', slug: 'infinix-note-40-pro',
    description_ar: 'إنفنكس نوت 40 برو بشحن لاسلكي 20W وكاميرا 108 ميجابكسل.',
    price: 9800, old_price: 11000, discount_percent: 11, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1530319067432-f2a729c03db5?w=800&q=80',
    condition: 'new', storage: '256GB', ram: '12GB', color: 'Vintage Green',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.5, review_count: 702, bought_recently: 451,
    brand: infinix, category: phones,
    images: [{ id: 11, image_url: 'https://images.unsplash.com/photo-1530319067432-f2a729c03db5?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 18, spec_name: 'الكاميرا', spec_value: '108MP Triple' }],
  },
  {
    id: 11, name_ar: 'هواوي ووتش GT 4', slug: 'huawei-watch-gt-4',
    description_ar: 'ساعة هواوي GT 4 بتصميم أنيق وعمر بطارية يصل إلى 14 يوماً.',
    price: 8500, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Stainless Steel',
    warranty: '12 شهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.0, review_count: 236, bought_recently: 162,
    brand: huawei, category: watches,
    images: [{ id: 12, image_url: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 19, spec_name: 'البطارية', spec_value: '14 days' }],
  },
  {
    id: 12, name_ar: 'شاحن Apple 20W USB-C', slug: 'apple-charger-20w',
    description_ar: 'شاحن Apple الأصلي 20W USB-C مع شحن سريع.',
    price: 850, old_price: 1100, discount_percent: 23, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'White',
    warranty: '6 أشهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.6, review_count: 738, bought_recently: 473,
    brand: apple, category: chargers,
    images: [{ id: 13, image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80', sort_order: 0 }],
    specs: [],
  },
  {
    id: 13, name_ar: 'أوبو رينو 11 برو', slug: 'oppo-reno-11-pro',
    description_ar: 'أوبو رينو 11 برو بكاميرا 50 ميجابكسل ومعالج Snapdragon 8 Gen 2.',
    price: 18500, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&q=80',
    condition: 'new', storage: '256GB', ram: '12GB', color: 'Pearl White',
    warranty: '12 شهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.7, review_count: 844, bought_recently: 539,
    brand: oppo, category: phones,
    images: [{ id: 14, image_url: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 20, spec_name: 'الشاشة', spec_value: '6.7" AMOLED 120Hz' }],
  },
  {
    id: 14, name_ar: 'ريلمي GT 5 برو', slug: 'realme-gt-5-pro',
    description_ar: 'ريلمي GT 5 برو بمعالج Snapdragon 8 Gen 3 وشحن سريع 100W.',
    price: 24500, old_price: 27000, discount_percent: 9, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=800&q=80',
    condition: 'new', storage: '512GB', ram: '16GB', color: 'Red Rover',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.2, review_count: 378, bought_recently: 250,
    brand: realme, category: phones,
    images: [{ id: 15, image_url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 21, spec_name: 'المعالج', spec_value: 'Snapdragon 8 Gen 3' }],
  },
  {
    id: 15, name_ar: 'سماعات Sony WH-1000XM5', slug: 'sony-wh-1000xm5',
    description_ar: 'سماعات Sony WH-1000XM5 — قمة عزل الضوضاء بصوت احترافي.',
    price: 11000, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Silver',
    warranty: '12 شهر', is_featured: true, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.7, review_count: 879, bought_recently: 561,
    brand: samsung, category: audio,
    images: [{ id: 16, image_url: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 22, spec_name: 'البطارية', spec_value: '30 hours' }],
  },
  {
    id: 16, name_ar: 'آيفون 13 (مستعمل)', slug: 'iphone-13-used',
    description_ar: 'آيفون 13 مستعمل بحالة ممتازة، بطارية 92%، شامل الكرتونة الأصلية.',
    price: 22000, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800&q=80',
    condition: 'used', storage: '128GB', ram: '4GB', color: 'Midnight',
    warranty: '3 أشهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.7, review_count: 809, bought_recently: 517,
    brand: apple, category: phones,
    images: [{ id: 17, image_url: 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 23, spec_name: 'الحالة', spec_value: 'مستعمل — بطارية 92%' }],
  },
  {
    id: 17, name_ar: 'سامسونج جالاكسي A55 5G', slug: 'samsung-galaxy-a55-5g',
    description_ar: 'جالاكسي A55 5G بشاشة Super AMOLED ومعالج Exynos 1480.',
    price: 13500, old_price: 15000, discount_percent: 10, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&q=80',
    condition: 'new', storage: '128GB', ram: '8GB', color: 'Awesome Iceblue',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.1, review_count: 342, bought_recently: 228,
    brand: samsung, category: phones,
    images: [{ id: 18, image_url: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 24, spec_name: 'الشاشة', spec_value: '6.6" Super AMOLED 120Hz' }],
  },
  {
    id: 18, name_ar: 'شاومي سمارت باند 9', slug: 'xiaomi-smart-band-9',
    description_ar: 'سوار شاومي 9 بشاشة AMOLED 1.62 إنش وعمر بطارية 21 يوماً.',
    price: 1450, old_price: 1750, discount_percent: 17, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Black',
    warranty: '6 أشهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.2, review_count: 413, bought_recently: 272,
    brand: xiaomi, category: watches,
    images: [{ id: 19, image_url: 'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 25, spec_name: 'البطارية', spec_value: '21 days' }],
  },
  {
    id: 19, name_ar: 'شاحن Samsung 45W Super Fast', slug: 'samsung-charger-45w',
    description_ar: 'شاحن سامسونج 45W الأصلي للشحن فائق السرعة.',
    price: 1200, old_price: 1450, discount_percent: 17, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'White',
    warranty: '6 أشهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.3, review_count: 449, bought_recently: 294,
    brand: samsung, category: chargers,
    images: [{ id: 20, image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80', sort_order: 0 }],
    specs: [],
  },
  {
    id: 20, name_ar: 'ساعة Apple Watch Ultra 2', slug: 'apple-watch-ultra-2',
    description_ar: 'Apple Watch Ultra 2 — أقوى ساعة آبل بهيكل تيتانيوم وشاشة 3000 نت.',
    price: 32000, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Natural Titanium',
    warranty: '12 شهر', is_featured: true, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.8, review_count: 950, bought_recently: 5,
    brand: apple, category: watches,
    images: [{ id: 21, image_url: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&q=80', sort_order: 0 }],
    specs: [
      { id: 26, spec_name: 'الشاشة', spec_value: '1.92" Retina 3000 nits' },
      { id: 27, spec_name: 'البطارية', spec_value: '36 hours' },
    ],
  },
  {
    id: 21, name_ar: 'آيفون 14 برو', slug: 'iphone-14-pro',
    description_ar: 'آيفون 14 برو بشاشة Always-On وكاميرا 48 ميجابكسل ومعالج A16 Bionic.',
    price: 44000, old_price: 48000, discount_percent: 8, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=800&q=80',
    condition: 'new', storage: '128GB', ram: '6GB', color: 'Deep Purple',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.6, review_count: 312, bought_recently: 200,
    brand: apple, category: phones,
    images: [{ id: 22, image_url: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=800&q=80', sort_order: 0 }],
    specs: [
      { id: 28, spec_name: 'الشاشة', spec_value: '6.1" Super Retina XDR' },
      { id: 29, spec_name: 'المعالج', spec_value: 'A16 Bionic' },
    ],
  },
  {
    id: 22, name_ar: 'شاومي ريدمي نوت 14 5G', slug: 'redmi-note-14-5g',
    description_ar: 'ريدمي نوت 14 5G بشاشة AMOLED 120 هرتز وكاميرا 108 ميجابكسل.',
    price: 12500, old_price: 14000, discount_percent: 11, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80',
    condition: 'new', storage: '256GB', ram: '8GB', color: 'Ocean Blue',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.7, review_count: 1240, bought_recently: 400,
    brand: xiaomi, category: phones,
    images: [{ id: 23, image_url: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 30, spec_name: 'الكاميرا', spec_value: '108MP Triple' }],
  },
  {
    id: 23, name_ar: 'تكنو سبارك 30 برو', slug: 'tecno-spark-30-pro',
    description_ar: 'تكنو سبارك 30 برو بكاميرا 108 ميجابكسل وشاشة AMOLED 120 هرتز.',
    price: 7200, old_price: 8500, discount_percent: 15, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1601972602288-3be527b4f1d8?w=800&q=80',
    condition: 'new', storage: '256GB', ram: '8GB', color: 'Magic Skin Orange',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.5, review_count: 95, bought_recently: 60,
    brand: tecno, category: phones,
    images: [{ id: 24, image_url: 'https://images.unsplash.com/photo-1601972602288-3be527b4f1d8?w=800&q=80', sort_order: 0 }],
    specs: [],
  },
  {
    id: 24, name_ar: 'ريلمي C75', slug: 'realme-c75',
    description_ar: 'ريلمي C75 بمقاومة الماء IP69 وبطارية ضخمة 6000 mAh.',
    price: 6500, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=800&q=80',
    condition: 'new', storage: '128GB', ram: '6GB', color: 'Storm Blue',
    warranty: '12 شهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.3, review_count: 67, bought_recently: 35,
    brand: realme, category: phones,
    images: [{ id: 25, image_url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 31, spec_name: 'البطارية', spec_value: '6000 mAh' }],
  },
  {
    id: 25, name_ar: 'إيربودز 4', slug: 'airpods-4',
    description_ar: 'AirPods 4 الجيل الجديد مع تصميم جديد وجودة صوت محسنة.',
    price: 5200, old_price: 5800, discount_percent: 10, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'White',
    warranty: '12 شهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.6, review_count: 410, bought_recently: 180,
    brand: apple, category: audio,
    images: [{ id: 26, image_url: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 32, spec_name: 'البطارية', spec_value: '5h + 30h case' }],
  },
  {
    id: 26, name_ar: 'باور بانك Anker 20000mAh', slug: 'anker-powerbank-20000',
    description_ar: 'باور بانك Anker بسعة 20000mAh مع شحن سريع 22.5W.',
    price: 1850, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Black',
    warranty: '18 شهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.1, review_count: 307, bought_recently: 206,
    brand: huawei, category: accessories,
    images: [{ id: 27, image_url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80', sort_order: 0 }],
    specs: [],
  },
  {
    id: 27, name_ar: 'كفر iPhone 15 Pro Max جلد', slug: 'iphone-15-promax-case',
    description_ar: 'كفر جلد طبيعي فاخر لـ iPhone 15 Pro Max مع MagSafe.',
    price: 750, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1601593346740-925612772716?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Brown',
    warranty: '3 أشهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.8, review_count: 915, bought_recently: 583,
    brand: apple, category: accessories,
    images: [{ id: 28, image_url: 'https://images.unsplash.com/photo-1601593346740-925612772716?w=800&q=80', sort_order: 0 }],
    specs: [],
  },
  {
    id: 28, name_ar: 'سماعات JBL Tune 770NC', slug: 'jbl-tune-770nc',
    description_ar: 'سماعات JBL Tune 770NC اللاسلكية مع إلغاء ضوضاء نشط وبطارية تدوم 70 ساعة.',
    price: 3200, old_price: 3800, discount_percent: 16, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'Black',
    warranty: '6 أشهر', is_featured: false, is_offer: true, is_active: true,
    stock_status: 'in_stock', rating: 4.6, review_count: 773, bought_recently: 495,
    brand: huawei, category: audio,
    images: [{ id: 29, image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 33, spec_name: 'البطارية', spec_value: '70 hours' }],
  },
  {
    id: 29, name_ar: 'هونر ماجيك V5', slug: 'honor-magic-v5',
    description_ar: 'هاتف Honor Magic V5 القابل للطي مع كاميرا متقدمة وشاشة AMOLED LTPO.',
    price: 56000, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=800&q=80',
    condition: 'new', storage: '512GB', ram: '16GB', color: 'Charcoal',
    warranty: '12 شهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.4, review_count: 188, bought_recently: 100,
    brand: huawei, category: phones,
    images: [{ id: 30, image_url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=800&q=80', sort_order: 0 }],
    specs: [{ id: 34, spec_name: 'الشاشة', spec_value: '7.92" LTPO AMOLED' }],
  },
  {
    id: 30, name_ar: 'كابل USB-C to Lightning 2م', slug: 'apple-usbc-lightning-2m',
    description_ar: 'كابل أصلي من Apple بطول 2 متر للشحن السريع ونقل البيانات.',
    price: 450, old_price: null, discount_percent: null, currency: 'MRU',
    main_image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    condition: 'new', storage: null, ram: null, color: 'White',
    warranty: '3 أشهر', is_featured: false, is_offer: false, is_active: true,
    stock_status: 'in_stock', rating: 4.1, review_count: 271, bought_recently: 184,
    brand: apple, category: chargers,
    images: [{ id: 31, image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80', sort_order: 0 }],
    specs: [],
  },
];
